# Generated by Django 4.0.2 on 2022-03-15 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
