# Generated by Django 4.0.2 on 2022-03-09 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 19, 0, 34, 423306), editable=False),
            preserve_default=False,
        ),
    ]
