# Generated by Django 4.0.2 on 2022-03-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
